export const categories = [
  {
    id: 1,
    name: "Pizza",
    image: require("../assets/images/pizzaIcon.png"),
  },
  {
    id: 2,
    name: "Burger",
    image: require("../assets/images/pizzaIcon.png"),
  },
  {
    id: 3,
    name: "Italian",
    image: require("../assets/images/pizzaIcon.png"),
  },
  {
    id: 4,
    name: "Chinese",
    image: require("../assets/images/pizzaIcon.png"),
  },
  {
    id: 5,
    name: "Noodles",
    image: require("../assets/images/pizzaIcon.png"),
  },
  {
    id: 6,
    name: "Sweets",
    image: require("../assets/images/pizzaIcon.png"),
  },
];

export const feautred = {
  id: 1,
  title: "Hot and spicy ",
  description: "soft and tender fried chicken",
  restaurant: [
    {
      id: 1,
      name: "Pizza Hut",
      image: require("../assets/images/pizzaHut.jpg"),
      description: "Hot and spicy pizza",
      lng: 	29.257639,
      lat: 	40.879848,
      adress: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Pizza",
          price: 10,
          description: "chezy garlic pizza",
          image: require("../assets/images/pizza.jpeg"),
        },
        {
          id: 2,
          name: "Pizza",
          price: 10,
          description: "chezy garlic pizza",
          image: require("../assets/images/pizza.jpeg"),
        },
        {
          id: 3,
          name: "Pizza",
          price: 10,
          description: "chezy garlic pizza",
          image: require("../assets/images/pizza.jpeg"),
        },
        {
          id: 4,
          name: "Pizza",
          price: 10,
          description: "chezy garlic pizza",
          image: require("../assets/images/pizza.jpeg"),
        },
      ],
    },
    {
      id: 2,
      name: "Pizza Hut",
      image: require("../assets/images/pizzaHut.jpg"),
      description: "Hot and spicy pizza",
      lng: 38.2145602,
      lat: -85.5324269,
      adress: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Pizza",
          price: 10,
          description: "chezy garlic pizza",
          image: require("../assets/images/pizzaIcon.png"),
        },
        {
          id: 2,
          name: "Pizza",
          price: 10,
          description: "chezy garlic pizza",
          image: require("../assets/images/pizzaIcon.png"),
        },
        {
          id: 3,
          name: "Pizza",
          price: 10,
          description: "chezy garlic pizza",
          image: require("../assets/images/pizzaIcon.png"),
        },
        {
          id: 4,
          name: "Pizza",
          price: 10,
          description: "chezy garlic pizza",
          image: require("../assets/images/pizzaIcon.png"),
        },
      ],
    },
    {
      id: 3,
      name: "Pizza Hut",
      image: require("../assets/images/pizzaHut.jpg"),
      description: "Hot and spicy pizza",
      lng: 38.2145602,
      lat: -85.5324269,
      adress: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Pizza",
          price: 10,
          description: "chezy garlic pizza",
          image: require("../assets/images/pizzaIcon.png"),
        },
        {
          id: 2,
          name: "Pizza",
          price: 10,
          description: "chezy garlic pizza",
          image: require("../assets/images/pizzaIcon.png"),
        },
        {
          id: 3,
          name: "Pizza",
          price: 10,
          description: "chezy garlic pizza",
          image: require("../assets/images/pizzaIcon.png"),
        },
        {
          id: 4,
          name: "Pizza",
          price: 10,
          description: "chezy garlic pizza",
          image: require("../assets/images/pizzaIcon.png"),
        },
      ],
    },
  ],
};
